SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 120


ENABLE_GRAPHICS = True

MAX_ALL_ATTRIBUTES_WOLFS = 100
MAX_ALL_ATTRIBUTES_LAMBS = 100

MIN_SPEED_WOLFS = 1
MAX_SPEED_WOLFS = MAX_ALL_ATTRIBUTES_WOLFS
MIN_ACCELERATION_WOLFS = 1
MAX_ACCELERATION_WOLFS = 10
MIN_FORCE_WOLFS = 1
MAX_FORCE_WOLFS = MAX_ALL_ATTRIBUTES_WOLFS
MIN_DEFENSE_WOLFS = 1
MAX_DEFENSE_WOLFS = MAX_ALL_ATTRIBUTES_WOLFS
MIN_VISION_RAY_WOLFS = 20
MAX_VISION_RAY_WOLFS = 50



MIN_SPEED_LAMBS = 1
MAX_SPEED_LAMBS = MAX_ALL_ATTRIBUTES_LAMBS
MIN_ACCELERATION_LAMBS = 1
MAX_ACCELERATION_LAMBS = 5
MIN_FORCE_LAMBS = 1
MAX_FORCE_LAMBS = 50
MIN_DEFENSE_LAMBS = 1
MAX_DEFENSE_LAMBS = 50
MIN_VISION_RAY_LAMBS = 20
MAX_VISION_RAY_LAMBS = 50



PROBABILITIE_COMPETITION = 0.1
PROBABILITIE_REPRODUCTION = 0.3
PROBABILITIE_MUTATION = 0.01

GRASSES_INCREMENT_PER_EPOCH = 5

MILLISECONDS_ONE_EPOCH = 1000

MAX_AGE = 100
DECREMENT_LIFES_PER_AGE = 5
